<a href="https://colab.research.google.com/github/Srishti-1307/dataEngineerTrainee/blob/main/array_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Numpy Arrays

In [ ]:
pythonList = [1,2,3,4,5,6]
numpyArray = np.array(pythonList)
print(numpyArray)
print('--------------------------------------------------------------------')
print(np.array([[1,2],[3,4],[4,5]]))
print('--------------------------------------------------------------------')
print(np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]))
print('--------------------------------------------------------------------')
print(np.array([1, 2, 3, 4], ndmin=5))

[1 2 3 4 5 6]
--------------------------------------------------------------------
[[1 2]
 [3 4]
 [4 5]]
--------------------------------------------------------------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
--------------------------------------------------------------------
[[[[[1 2 3 4]]]]]


In [ ]:
# Dimension

print(np.array([[1,2],[3,4],[4,5]]).ndim)

2


In [ ]:
pythonTuple = (5,6,7,8,9)
numpyArray = np.array(pythonTuple)
print(numpyArray)
print(np.array(((13,14,15,16), (1,2,3,4))))

[5 6 7 8 9]
[[13 14 15 16]
 [ 1  2  3  4]]


In [ ]:
arrayZeros = np.zeros((2,4), dtype=np.int64)
print(arrayZeros)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
arrayOnes = np.ones(7)
print(arrayOnes)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arrayFull = np.full((3,3),7)
print(arrayFull)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
arrayArange = np.arange(5,20,2)       # start , stop , step
print(arrayArange)

[ 5  7  9 11 13 15 17 19]


In [ ]:
arrayLinspace = np.linspace(1,10,7)     # start, stop, num (equispaced)
print(arrayLinspace)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [ ]:
# random number generation

In [ ]:
arr1 = np.random.rand(6,2)                       # between 0 & 1
print(arr1)

[[0.17652122 0.65568232]
 [0.93932164 0.75014321]
 [0.63441671 0.32210214]
 [0.65046377 0.92970142]
 [0.58602635 0.5448748 ]
 [0.93501896 0.69926062]]


In [ ]:
arr2 = np.random.randn(10)                          # between -1 & 1
print(arr2)

[ 0.02901246 -1.57458184 -0.17009651 -0.39571983  0.51493584 -0.50472258
 -0.2134651  -0.80681861 -0.2487842  -0.08463745]


In [ ]:
arr3 = np.random.randint(4,12, (4,2))                # from, to, shape
print(arr3)

[[ 5  7]
 [ 9  9]
 [10 11]
 [11  6]]


In [ ]:
# np.eye() v/s np.identity()

In [ ]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.eye(4))      # np.eye(row, col, diagonal, dtype) by-default col=row; diagonal=0 (try 0,1,2,3,4); dtype=float

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
