<a href="https://colab.research.google.com/github/Srishti-1307/dataEngineerTrainee/blob/main/ex7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  Generate a 2D NumPy array with random integers (10x5) representing temperature readings.

In [ ]:
import numpy as np

In [ ]:
temp_readings = np.random.randint(20,30,(2,10,5))
print(temp_readings)

[[[29 29 28 27 21]
  [27 29 26 27 23]
  [25 27 21 21 27]
  [21 23 25 25 21]
  [21 20 27 27 20]
  [29 20 23 22 20]
  [24 20 21 25 26]
  [28 28 29 26 23]
  [28 29 27 27 28]
  [27 25 20 24 27]]

 [[26 26 24 26 29]
  [26 27 21 22 26]
  [24 23 28 27 24]
  [22 26 25 20 29]
  [21 21 25 24 24]
  [22 29 29 24 24]
  [26 22 28 23 25]
  [27 25 24 24 23]
  [29 29 25 26 22]
  [20 25 21 23 20]]]
