<a href="https://colab.research.google.com/github/Srishti-1307/dataEngineerTrainee/blob/main/indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1,2,0])    # depth, row, col

16


In [ ]:
# slicing example 1

arr1 = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
2


In [ ]:
print(arr1[0:2, 1:3])                #  arr[row , col]

[[2 3]
 [4 5]]


In [ ]:
# slicing example 2
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(arr2[: , 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
# boolean indexing
arr3 = np.array((23,13,65,34,32,18,11))
print(arr3[arr3>20])
print(arr3[(arr3>20) & (arr3<50)])

[23 65 34 32]
[23 34 32]


In [ ]:
print(np.array([arr3>20]))

[[ True False  True  True  True False False]]


In [ ]:
indices = [0,2,4]                        #fancy indexing
print(arr3[indices])

[23 65 32]


In [ ]:
arr4= np.array([1,2,3])
# np.newaxis keyword adds a new axis to the array which helps in converting a 1D array into a row or column vector.
print(arr4[:, np.newaxis])

[[1]
 [2]
 [3]]


In [ ]:
# dtype
# For i, u, f, S and U we can define size as well; like

In [ ]:
fruits = np.array(['apple', 'mango', 'banana'])
print(fruits.dtype)

<U6


In [ ]:
fruitsS = np.array(['apple', 'mango', 'banana'],dtype = 'S')

In [ ]:
arr5 = np.array([1.1, 2.1, 32.1, 45.8])
arr6 = arr5.astype('i')                          # or try:  arr5.astype(int)
print(arr6)

[ 1  2 32 45]


In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(str(array))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
testArray = np.array([[1,2,3],[4,5,6]])
testArray

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(testArray[[0, 1, 1], [0, 1, 2]])

[1 5 6]
