<a href="https://colab.research.google.com/github/Srishti-1307/dataEngineerTrainee/blob/main/shape_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = arr1.reshape(2,2,-1)                       # Pass -1 as the value, and NumPy will calculate this number for you.
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3  = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('--------------------------------------------')
print(arr3.reshape(-1))

[[1 2 3]
 [4 5 6]]
--------------------------------------------
[1 2 3 4 5 6]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
