## Numpy/nd-Array Creation Methods

1) np.array()

2) np.zeros/ones/empty/random()

3) np.arange() 

4) np.linspace()

5) copy()

6. identity()

In [6]:
import numpy as np

In [10]:
arr1= np.array([1,3,0,7,2,0,0,3])       
arr1

array([1, 3, 0, 7, 2, 0, 0, 3])

In [11]:
arr2= np.array([[2,1,0,1],[2,9,1,1],[1,6,0,8]])
arr2

array([[2, 1, 0, 1],
       [2, 9, 1, 1],
       [1, 6, 0, 8]])

In [92]:
arr3= np.zeros((2,4), dtype='int32')
arr3

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [93]:
arr4= np.ones((5,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
arr5= np.identity(6)
arr5

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [70]:
arr6= np.arange(2,14,2)                                    #np.arange(kaha se, kaha tk, step-size)
arr6

array([ 2,  4,  6,  8, 10, 12])

In [75]:
arr7= np.linspace(1,10,20)                                  #np.linspace(kaha se, kaha tk, kitne)
arr7

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [74]:
arr8= arr7.copy()                                        #A copy of arr7 array
arr8

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [3]:
arr10= np.random.randint(low=1, high=25, size=20).reshape(4,5)             
arr10

array([[ 5, 10,  5, 24, 14],
       [ 7, 19, 15, 12,  9],
       [12, 14, 16, 12,  2],
       [23,  9,  1,  7, 18]], dtype=int32)

In [5]:
# you can use "np.random.randint(1,25,20)" this instead
# np.random.rand(10)                -- Generates random numbers from a uniform distribution between 0 and 1.
# np.random.randint(1,10,15)       -- Generates random integers within a specified range.
#a= np.random.randn(10)           -- Generates 10 random numbers from normal distribution


## Numpy Properties & Attributes

1) Shape

2) ndim

3) Size

4) Itemsize

5) Dtype

6) astype()

The ones which are properties don't use () at the end... attributes use '()'

In [10]:
arr9= np.array([[[1,2,9],[3,4,8]],[[1,2,7],[3,4,6]],[[1,2,5],[3,4,4]]])
arr9

array([[[1, 2, 9],
        [3, 4, 8]],

       [[1, 2, 7],
        [3, 4, 6]],

       [[1, 2, 5],
        [3, 4, 4]]])

In [11]:
arr9.shape                       #returns (dimension, rows(in each), col(in each))

(3, 2, 3)

In [12]:
arr9.ndim                        #Gives dimension

3

In [13]:
arr9.size

18

In [14]:
arr9.itemsize                      #your system has 64-bit int architecture, therefore each item (element) will take 8 Bytes

8

In [15]:
arr9.dtype

dtype('int64')

In [95]:
arr4.dtype

dtype('float64')

In [96]:
arr4_= arr4.astype('int')     
arr4_

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [97]:
arr4_.dtype
#But arr4.dtype still float 64 return krega.
#Qki arr4.astype('int') ek naya integer array banta hai, original change nahi hota. Isliye dtype still float64 dikh raha hai.

dtype('int64')

In [62]:
arra = np.zeros((2, 3, 4, 5), dtype=int)  # 4D array with shape (2,3,4,5)
print(arra)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]


In [24]:
a= np.linspace(1,10,8)
a

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])