#### 1D array  --- vector---  axis = 0 

#### 2D array -- matrix ---- 
* axis = 0 (refers to the rows) Vertical; operations are performed along col.
* axis = 1 (refers to the col) Horizontal; operations are performed row-wise. 

#### Negative indexing
* Negative axis values can be used to refer to axes from the end of the array.
* For example, axis=-1 refers to the last axis, axis=-2 refers to the second to last axis, and so on...
* In a 2D array, axis=-1 is equivalent to axis=1, and axis=-2 is equivalent to axis=0

In [2]:
import  numpy as np

In [3]:
arr1 = np.array([[1,2,3,4],[4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [5]:
arr1Axis0Sum = np.sum(arr1, axis = 0) 
arr1Axis0Sum

array([ 5,  7,  9, 11])

In [6]:
arr1Axis1Sum = np.sum(arr1, axis = 1)
arr1Axis1Sum

array([10, 22])

#### Boolean Indexing
* It involves creating a "Boolean mask" which is a NumPy array of True and False values, and then using this mask to index the original array.


In [37]:
arr2 = np.array([34,65,45,65,98,102,21,37])                # the original array
arr2

array([ 34,  65,  45,  65,  98, 102,  21,  37])

In [41]:
mask = arr2 > 50                                            # creating mask
mask

array([False,  True, False,  True,  True,  True, False, False])

In [18]:
arr2[mask]                                                # boolean indexing helped to get only those elements from arr2  which are > 50 

array([ 65,  65,  98, 102])

In [20]:
arr2[arr2>50]                              # directly also works!

array([ 65,  65,  98, 102])

In [34]:
# making elements below 50 = 0  THIS IS NOTHING BUT CONDITIONAL REPLACEMENT.
arr2[arr2<50] = 00                                    # creating changes in original array!
arr2

array([  0,  65,   0,  65,  98, 102,   0,   0])

In [42]:
# Conditional replacement method - 2   ----- using where function ------ where(condition, newValue, array)
arr2New = np.where((arr2 < 50) & (arr2>30), 0, arr2)
arr2New

array([  0,  65,   0,  65,  98, 102,  21,   0])

##### Key difference
* Boolean indexing modifies the array in-place, while np.where() typically returns a new array.