In [1]:
import numpy as np

In [2]:
a1= np.arange(9).reshape(3,3)
a2= np.array([0,1,2])

In [6]:
print(a1, a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [0 1 2]


In [7]:
a1+a2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

#### Above you saw that.... a1 is 3x3 and a2 is 1x3 still addition is being possible. This is due to Broadcasting

### Broadcasting......??   The smaller array is upgraded to the size of larger array so that they have compatible shapes. 

##### if broadcasting was't there... we we would be restricted to perform operations on same-sized arrays. 
Below we'll see where the Broadcasting is allowed...

In [3]:
arr1= np.arange(3).reshape(1,3)
arr2= np.arange(12).reshape(4,3)
print(arr1)
print(arr2)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


###### if there's any 1 charo me se... and corresponding bagal wala no is same in both.. (like 3 here), then allowed.

In [4]:
arr1+arr2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [6]:
arr1= np.arange(4).reshape(4,1)
arr2= np.arange(12).reshape(4,3)
print(arr1)
print(arr2)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
arr1+arr2                          #here also there's one 1 and corresponding bagal wale are same.

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [9]:
#if there's a 1 but saamne wale are not same ex- (1,3) and (4,4)/(3,4) then addition not allowed!

##### now if there are two 1s and bagal wale same then addition allowed!

In [13]:
arr1= np.arange(4).reshape(4,1)
arr2= np.arange(4).reshape(1,4)
print(arr1)
print(arr2)

[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]]


In [14]:
arr1+arr2                                    

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

##### if there's one 1 element array (singleton) and doosri wali kuch bhi.... then also allowed.

In [18]:
arr1= np.arange(1)
arr2= np.arange(12).reshape(3,4)
print(arr1)
print(arr2)

[0]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
arr1+arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### another example where addition by broadcasting is allowed

In [20]:
arr1= np.arange(4)
arr2= np.arange(12).reshape(3,4)
print(arr1)
print(arr2)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
arr1+arr2

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])