In [38]:
import numpy as np

### Loading txt and csv files

#### 1) numpy.loadtxt()

In [11]:
arr1 = np.loadtxt('demo.csv', delimiter=',')
print(arr1)

[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]
 [5. 6. 7. 8. 9.]]


#### 2) numpy.genfromtxt()

In [44]:
arr2 = np.genfromtxt('data.csv', delimiter=',', dtype=None, encoding=None)

In [45]:
arr2

array([['"f1"', '"f2"', '"f3"', ..., '"f616"', '"f617"', '"class"'],
       ['-0.4394', '-0.093', '0.1718', ..., '0.5898', '-0.4872', "'1'"],
       ['-0.4348', '-0.1198', '0.2474', ..., '0.4546', '-0.091', "'1'"],
       ...,
       ['-0.6696', '-0.373', '0.1584', ..., '0.0728', '-0.5818', "'25'"],
       ['-0.5764', '-0.1764', '0.5106', ..., '-0.0434', '-0.5', "'26'"],
       ['-0.6624', '-0.3334', '0.3666', ..., '-0.1708', '-0.317', "'26'"]],
      shape=(7798, 618), dtype='<U7')

In [86]:
a2 = np.ones(5)

In [78]:
a1 = np.array([32,13,42,21,33])

In [87]:
np.append(a1, a2)

array([42., 33., 32., 21., 13.,  1.,  1.,  1.,  1.,  1.])

In [75]:
a1

array([[13, 21, 32, 33, 42],
       [11, 12, 23, 42, 44]])

In [95]:
arr5

array([[14,  5, 17, 24,  1,  9, 17, 25, 18, 22, 27, 11, 24, 14, 28, 19,
        25,  9, 29,  8,  6,  8,  7,  8],
       [24, 18,  3, 26,  2, 19, 11, 14, 23, 13,  3, 20, 13,  2,  9, 21,
        22,  9, 19, 20, 23,  2, 25, 21],
       [14, 17, 13, 29, 24, 19,  8, 13, 11, 24, 20,  1, 17, 27,  9, 10,
        13, 22, 13,  9, 13, 25,  6, 26],
       [18,  9, 15, 24, 20, 17, 19, 20,  7,  2,  1, 28, 20, 11, 21, 20,
         8, 12,  7, 10, 21,  9, 12,  5],
       [ 4, 28, 11,  7,  9, 11, 20, 18, 13,  8, 22,  7, 23, 24, 23,  2,
        24, 14,  7, 10, 11, 14, 25, 13],
       [ 8, 14, 26, 26, 10, 12, 13, 19, 16, 17,  3,  3, 13, 10, 16, 29,
        24, 20, 17, 17,  4,  6,  8, 20],
       [27, 16, 21, 13,  3,  4,  5, 13, 22, 14, 26, 19, 19, 20, 20, 22,
         2, 11, 14,  8, 28, 14,  1,  9]])

[375 362 383 336 348 351 351]


[15.62 15.08 15.96 14.   14.5  14.62 14.62]


[67.57 63.91 52.46 50.   53.58 52.15 62.07]
