In [1]:
import numpy as np

In [2]:
arr5 = np.random.randint(1,30, size=(7,24))

In [6]:
arr5

array([[17,  4, 26,  2, 25, 18,  9,  4, 19, 10, 17, 10, 21, 22,  7, 14,
         8, 12, 14, 22, 19, 24, 18, 10],
       [ 4, 20,  9,  2, 17, 15, 28,  9, 26, 13, 22, 24,  9, 10,  7, 17,
        25, 25, 27, 12,  8,  7, 29,  1],
       [ 7, 17, 21,  5, 21, 19, 27,  8, 27, 18, 26, 24, 23,  6, 27, 27,
        15, 16, 23, 19, 28,  8, 11,  1],
       [17, 12,  3,  9, 15, 11,  5, 10, 21, 12, 17, 15,  1,  1,  5, 29,
        11, 10, 11, 21, 29, 22,  9, 15],
       [15, 10,  3,  8,  4, 25, 25, 15,  5,  8, 26, 23, 22, 11,  3,  7,
        26,  2, 22,  6,  4, 25, 28,  8],
       [28,  7, 26, 16, 18,  1, 20,  4, 26, 10, 23, 11, 11,  2, 26, 26,
        14,  7, 17,  3, 19,  5, 29, 18],
       [14, 10,  7, 13, 19,  3,  2, 21, 28, 18, 21,  6, 10, 19,  6, 20,
        26,  6, 29,  2,  3,  4, 17,  7]])

In [3]:
print(np.sum(arr5, axis=1))

[352 366 424 311 331 367 311]


In [4]:
print(np.round(np.mean(arr5, axis=1),decimals=2))

[14.67 15.25 17.67 12.96 13.79 15.29 12.96]


In [5]:
print(np.round(np.var(arr5, axis=1),decimals=2))

[47.39 75.02 65.72 56.04 82.08 78.79 70.87]
