In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(10,100, size=(7,6))
arr1

array([[88, 56, 71, 22, 37, 34],
       [90, 90, 55, 36, 87, 27],
       [33, 36, 79, 26, 90, 55],
       [80, 84, 50, 81, 90, 47],
       [88, 93, 33, 19, 33, 14],
       [68, 71, 86, 33, 23, 71],
       [98, 40, 12, 79, 69, 64]])

#### Computing the average per sensor.

In [6]:
avg_per_sensor = np.round((np.average(arr1, axis=0)), decimals = 2)
avg_per_sensor

array([77.86, 67.14, 55.14, 42.29, 61.29, 44.57])

#### Finding the day with maximum total reading.

In [7]:
total_reading_per_day = np.sum(arr1, axis=1)
total_reading_per_day

array([308, 385, 319, 432, 280, 352, 362])

In [11]:
np.argmax(total_reading_per_day)

np.int64(3)